# Generated by Django 4.0.6 on 2022-07-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_rating_movi_alter_rewies_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Актер', 'verbose_name_plural': 'Актеры и Режиссеры'},
        ),
        migrations.AlterModelOptions(
            name='movieshots',
            options={'verbose_name': 'Кадр из фильма', 'verbose_name_plural': 'Кадры из фильма'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='fess_in_world',
            field=models.PositiveIntegerField(default=0, help_text='Указывать сумму в долларах', verbose_name='Сборы в мире'),
        ),
    ]
